### ISSUE TITLE
Miscellaneous TODO

### ISSUE THREAD

**Issue by gklyne** [gklyne/annalist#9]
This list should be reviewed broken out into separate issues, or moved to other issues.
- [x] view collections doesn't use entered label - problem with entry vocab? (Fixed)
- [x] move entity I/O logic in util module to entity module (keep it all together)
- [x] abstract definition of `field_context` - currently defined implicitly in `views.entityeditbase` (overtaken by redesign)
